'use client';
import Link from 'next/link';
import { Bot, Building2, ChevronDown, LayoutDashboard, MessageSquare, Settings, Users, Zap, Search, Plus } from 'lucide-react';

const stats = [ ['Conversas ativas', '38', '+12%'], ['Novos leads', '124', '+8%'], ['Taxa de resposta', '94%', '+4%'], ['Vendas no mês', 'R$ 28.750', '+18%'] ];
const conversations = [ ['Mariana Costa', 'Quero saber o preço do plano Pro', 'Agora', 'MC'], ['Rafael Mendes', 'Vocês entregam em todo o Brasil?', '5 min', 'RM'], ['Camila Oliveira', 'Perfeito, vou analisar e retorno!', '12 min', 'CO'], ['João Pedro', 'Gostaria de agendar uma demonstração', '28 min', 'JP'] ];
export default function Home() {
  return <div className="min-h-screen flex">
    <aside className="w-64 bg-ink text-white p-5 hidden md:block"><Link href="/" className="flex items-center gap-2 text-xl font-bold mb-10"><div className="bg-mint text-ink rounded-lg p-2"><Zap size={19}/></div>VendaFlow</Link><p className="text-xs uppercase tracking-wider text-slate-400 mb-3">Workspace</p>{[['Visão geral','/',LayoutDashboard],['Conversas','/conversations',MessageSquare],['Leads e CRM','/crm',Users],['Base de conhecimento','/knowledge',Building2],['Meu agente IA','/agent',Bot],['Configurações','/settings',Settings]].map(([label,href, Icon])=><Link key={String(label)} href={String(href)} className="w-full flex items-center gap-3 px-3 py-3 rounded-lg text-sm mb-1 text-slate-300 hover:bg-white/10 hover:text-mint"><Icon size={17}/>{String(label)}</Link>)}<div className="border-t border-white/10 mt-8 pt-5"><p className="text-xs text-slate-400">Plano atual</p><div className="flex justify-between mt-2"><span className="font-semibold">Professional</span><span className="text-mint">Ativo</span></div></div></aside>
    <main className="flex-1 p-5 md:p-8 max-w-[1500px]"><header className="flex justify-between items-center mb-8"><div><p className="text-sm text-slate-500">Quarta-feira, 03 de setembro de 2026</p><h1 className="text-2xl md:text-3xl font-bold mt-1">Visão geral</h1></div><div className="flex items-center gap-4"><button className="p-2 text-slate-500"><Search size={19}/></button><Link href="/profile" className="flex items-center gap-3 hover:opacity-80"><div className="bg-violet-100 text-violet-700 rounded-full h-9 w-9 flex items-center justify-center text-sm font-bold">AS</div><div className="hidden md:block"><p className="text-sm font-semibold">Aline Souza</p><p className="text-xs text-slate-500">Administradora</p></div><ChevronDown size={15}/></Link></div></header>
      <div className="flex items-center justify-between mb-4"><div><h2 className="font-bold text-lg">Bom dia, Aline 👋</h2><p className="text-sm text-slate-500">Aqui está o resumo da sua operação hoje.</p></div><button className="bg-ink text-white rounded-lg px-4 py-2.5 text-sm flex gap-2 items-center"><Plus size={16}/> Novo lead</button></div>
      <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">{stats.map(([title,value,trend])=><div className="card p-5" key={title}><p className="text-sm text-slate-500">{title}</p><div className="flex items-end justify-between mt-3"><strong className="text-2xl">{value}</strong><span className="text-xs text-emerald-600 bg-emerald-50 rounded-full px-2 py-1">{trend}</span></div><div className="h-1 bg-slate-100 rounded-full mt-5"><div className="h-1 bg-mint rounded-full w-3/4"/></div></div>)}</section>
      <section className="grid xl:grid-cols-3 gap-5"><div className="card xl:col-span-2 p-5"><div className="flex justify-between items-center mb-5"><div><h3 className="font-bold">Conversas recentes</h3><p className="text-sm text-slate-500">Acompanhe o atendimento do seu agente</p></div><Link href="/conversations" className="text-sm text-mint font-semibold">Ver todas</Link></div>{conversations.map(([name,message,time,initials])=><div className="flex items-center gap-3 py-3 border-t border-slate-100" key={name}><div className="bg-slate-100 rounded-full h-10 w-10 flex items-center justify-center text-xs font-bold text-slate-600">{initials}</div><div className="flex-1 min-w-0"><div className="flex justify-between"><p className="font-semibold text-sm">{name}</p><span className="text-xs text-slate-400">{time}</span></div><p className="text-sm text-slate-500 truncate mt-1">{message}</p></div><span className="h-2 w-2 rounded-full bg-mint"/></div>)}</div><div className="card p-5"><div className="flex justify-between mb-5"><div><h3 className="font-bold">Seu agente IA</h3><p className="text-sm text-slate-500">Status em tempo real</p></div><span className="bg-emerald-50 text-emerald-700 text-xs px-2.5 py-1 rounded-full">● Online</span></div><div className="bg-ink rounded-xl p-5 text-white"><div className="flex items-center gap-3"><div className="bg-mint text-ink rounded-lg p-2"><Bot size={22}/></div><div><p className="font-bold">Luna</p><p className="text-xs text-slate-300">Agente de vendas</p></div></div><p className="text-sm text-slate-300 mt-5 leading-relaxed">Sua agente está atendendo clientes, qualificando leads e respondendo dúvidas automaticamente.</p><div className="flex justify-between text-xs mt-5 pt-4 border-t border-white/10"><span>Conversas hoje</span><strong>86</strong></div></div><Link href="/agent" className="block text-center w-full mt-4 border border-slate-200 rounded-lg py-2.5 text-sm font-semibold">Configurar agente</Link></div></section>
    </main></div>;
}
